// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function alert(message) {
  if ((typeof window !== 'undefined' && window.alert)) {
    return (window.alert(message));
  }
}

function mixinMissingIssue(envSafe, issue) {
  let missingIssues = envSafe.maybeMissingIssues;
  if (missingIssues !== undefined) {
    missingIssues.push(issue);
  } else {
    envSafe.maybeMissingIssues = [issue];
  }
}

function mixinInvalidIssue(envSafe, issue) {
  let invalidIssues = envSafe.maybeInvalidIssues;
  if (invalidIssues !== undefined) {
    invalidIssues.push(issue);
  } else {
    envSafe.maybeInvalidIssues = [issue];
  }
}

function make(envOpt) {
  let env = envOpt !== undefined ? envOpt : process.env;
  return {
    env: env,
    isLocked: false,
    maybeMissingIssues: undefined,
    maybeInvalidIssues: undefined
  };
}

function close(envSafe) {
  if (envSafe.isLocked) {
    throw new Error(`[rescript-envsafe] ` + "EnvSafe is already closed.");
  }
  envSafe.isLocked = true;
  let match = envSafe.maybeMissingIssues;
  let match$1 = envSafe.maybeInvalidIssues;
  if (match === undefined && match$1 === undefined) {
    return;
  }
  let line = "========================================";
  let output = [line];
  if (match$1 !== undefined) {
    let invalidIssues = Primitive_option.valFromOption(match$1);
    output.push("❌ Invalid environment variables:");
    invalidIssues.forEach(issue => {
      output.push(`    ` + issue.name + `: ` + issue.error.message);
    });
  }
  if (match !== undefined) {
    let missingIssues = Primitive_option.valFromOption(match);
    output.push("💨 Missing environment variables:");
    missingIssues.forEach(issue => {
      let match = issue.input;
      let tmp;
      tmp = match === "" ? "Disallowed empty string" : "Missing value";
      output.push(`    ` + issue.name + `: ` + tmp);
    });
  }
  output.push(line);
  let text = output.join("\n");
  console.error(text);
  alert(text);
  throw new TypeError(text);
}

function coercionTarget(schema) {
  if (schema.type !== "anyOf") {
    return schema;
  }
  let match = schema.anyOf.filter(member => member.type !== "undefined");
  if (match.length !== 1) {
    return;
  } else {
    return match[0];
  }
}

function coerceString(string, schema) {
  switch (schema.type) {
    case "never" :
    case "string" :
      return string;
    case "number" :
      let float = (+string);
      if (Number.isNaN(float)) {
        return string;
      } else {
        return float;
      }
    case "bigint" :
      try {
        return BigInt(string);
      } catch (exn) {
        return string;
      }
    case "boolean" :
      switch (string) {
        case "0" :
        case "f" :
        case "false" :
          return false;
        case "1" :
        case "t" :
        case "true" :
          return true;
        default:
          return string;
      }
    default:
      try {
        return JSON.parse(string);
      } catch (exn$1) {
        return string;
      }
  }
}

function carriesOwnLogic(schema) {
  if ((s => s.refiner !== undefined)(schema)) {
    return true;
  } else {
    return Stdlib_Option.isSome(schema.to);
  }
}

function coerceUnion(schema) {
  if (schema.type === "anyOf" && !carriesOwnLogic(schema)) {
    return Sury.union(schema.anyOf.map(member => S.to(Sury.any, member, {
      decode: {
        TAG: "Sync",
        _0: input => coerceString(input, member)
      },
      encode: "never"
    })));
  } else {
    return schema;
  }
}

function get(envSafe, name, schema, allowEmptyOpt, maybeFallback, maybeDevFallback, maybeInlinedInput) {
  let allowEmpty = allowEmptyOpt !== undefined ? allowEmptyOpt : false;
  if (envSafe.isLocked) {
    throw new Error(`[rescript-envsafe] ` + "EnvSafe is closed. Make a new one to get access to environment variables.");
  }
  let input = maybeInlinedInput !== undefined ? Primitive_option.valFromOption(maybeInlinedInput) : envSafe.env[name];
  let isMissing = input !== undefined ? (
      input === "" ? !allowEmpty : false
    ) : true;
  let isOptional;
  if (schema.type === "anyOf") {
    let match = schema.has.undefined;
    isOptional = match !== undefined ? match : false;
  } else {
    isOptional = false;
  }
  if (isMissing && !isOptional) {
    if (maybeDevFallback !== undefined && envSafe.env["NODE_ENV"] !== "production") {
      return Primitive_option.valFromOption(maybeDevFallback);
    }
    if (maybeFallback !== undefined) {
      return Primitive_option.valFromOption(maybeFallback);
    } else {
      mixinMissingIssue(envSafe, {
        name: name,
        input: input
      });
      return undefined;
    }
  }
  let target = coercionTarget(schema);
  let input$1;
  if (input !== undefined) {
    let exit = 0;
    if (input === "" && !allowEmpty) {
      input$1 = undefined;
    } else {
      exit = 1;
    }
    if (exit === 1) {
      input$1 = target !== undefined ? coerceString(input, target) : input;
    }
  } else {
    input$1 = undefined;
  }
  let schema$1 = target !== undefined ? schema : coerceUnion(schema);
  try {
    return Sury.parseOrThrow(input$1, schema$1);
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === S.Exn) {
      mixinInvalidIssue(envSafe, {
        name: name,
        error: error._1,
        input: input$1
      });
      return undefined;
    }
    throw error;
  }
}

export {
  make,
  close,
  get,
}
/* S Not a pure module */
