// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function alert(message) {
  if ((typeof window !== 'undefined' && window.alert)) {
    return (window.alert(message));
  }
}

function mixinMissingIssue(envSafe, issue) {
  let missingIssues = envSafe.maybeMissingIssues;
  if (missingIssues !== undefined) {
    missingIssues.push(issue);
  } else {
    envSafe.maybeMissingIssues = [issue];
  }
}

function mixinInvalidIssue(envSafe, issue) {
  let invalidIssues = envSafe.maybeInvalidIssues;
  if (invalidIssues !== undefined) {
    invalidIssues.push(issue);
  } else {
    envSafe.maybeInvalidIssues = [issue];
  }
}

function make(envOpt) {
  let env = envOpt !== undefined ? envOpt : process.env;
  return {
    env: env,
    isLocked: false,
    maybeMissingIssues: undefined,
    maybeInvalidIssues: undefined
  };
}

function close(envSafe) {
  if (envSafe.isLocked) {
    throw new Error(`[rescript-envsafe] ` + "EnvSafe is already closed.");
  }
  envSafe.isLocked = true;
  let match = envSafe.maybeMissingIssues;
  let match$1 = envSafe.maybeInvalidIssues;
  if (match === undefined && match$1 === undefined) {
    return;
  }
  let line = "========================================";
  let output = [line];
  if (match$1 !== undefined) {
    let invalidIssues = Primitive_option.valFromOption(match$1);
    output.push("❌ Invalid environment variables:");
    invalidIssues.forEach(issue => {
      output.push(`    ` + issue.name + `: ` + issue.error.message);
    });
  }
  if (match !== undefined) {
    let missingIssues = Primitive_option.valFromOption(match);
    output.push("💨 Missing environment variables:");
    missingIssues.forEach(issue => {
      output.push(`    ` + issue.name + `: Missing value`);
    });
  }
  output.push(line);
  let text = output.join("\n");
  console.error(text);
  alert(text);
  throw new TypeError(text);
}

function needsJsonReading(member) {
  switch (member.type) {
    case "never" :
    case "string" :
    case "number" :
    case "bigint" :
    case "boolean" :
      return false;
    default:
      return true;
  }
}

function coerceWith(schema, member) {
  if (needsJsonReading(member)) {
    return S.to(Sury.jsonString, schema, undefined);
  } else {
    return S.to(Sury.env, schema, undefined);
  }
}

function carriesOwnLogic(schema) {
  if ((s => s.refiner !== undefined)(schema)) {
    return true;
  } else {
    return Stdlib_Option.isSome(schema.to);
  }
}

function coerceSchema(schema) {
  if (schema.type !== "anyOf") {
    return coerceWith(schema, schema);
  }
  let anyOf = schema.anyOf;
  if (carriesOwnLogic(schema)) {
    return schema;
  }
  let members = anyOf.filter(member => member.type !== "undefined");
  let tags = members.map(member => member.type);
  let match = members[0];
  let match$1 = tags[0];
  if (match !== undefined && match$1 !== undefined) {
    if (tags.every(tag => tag === match$1)) {
      return coerceWith(schema, match);
    } else {
      return Sury.union(anyOf.map(member => {
        if (member.type === "undefined") {
          return member;
        } else {
          return coerceWith(member, member);
        }
      }));
    }
  } else {
    return schema;
  }
}

function get(envSafe, name, schema, maybeFallback, maybeDevFallback, maybeInlinedInput) {
  if (envSafe.isLocked) {
    throw new Error(`[rescript-envsafe] ` + "EnvSafe is closed. Make a new one to get access to environment variables.");
  }
  let input = maybeInlinedInput !== undefined ? Primitive_option.valFromOption(maybeInlinedInput) : envSafe.env[name];
  let isMissing = input === undefined;
  let isOptional;
  if (schema.type === "anyOf") {
    let match = schema.has.undefined;
    isOptional = match !== undefined ? match : false;
  } else {
    isOptional = false;
  }
  if (isMissing && !isOptional) {
    if (maybeDevFallback !== undefined && envSafe.env["NODE_ENV"] !== "production") {
      return Primitive_option.valFromOption(maybeDevFallback);
    }
    if (maybeFallback !== undefined) {
      return Primitive_option.valFromOption(maybeFallback);
    } else {
      mixinMissingIssue(envSafe, {
        name: name
      });
      return undefined;
    }
  }
  let input$1 = Stdlib_Option.map(input, string => {
    switch (schema.type) {
      case "boolean" :
        break;
      case "anyOf" :
        let match = schema.has.boolean;
        if (match === undefined) {
          return string;
        }
        if (!match) {
          return string;
        }
        break;
      default:
        return string;
    }
    switch (string) {
      case "0" :
      case "f" :
        return "false";
      case "1" :
      case "t" :
        return "true";
      default:
        return string;
    }
  });
  try {
    return Sury.parseOrThrow(input$1, coerceSchema(schema));
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === S.Exn) {
      mixinInvalidIssue(envSafe, {
        name: name,
        error: error._1,
        input: input$1
      });
      return undefined;
    }
    throw error;
  }
}

export {
  make,
  close,
  get,
}
/* S Not a pure module */
