// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var S = require("rescript-struct/src/S.bs.js");
var Js_dict = require("rescript/lib/js/js_dict.js");

var value = {
  env: process.env
};

function get(key, struct) {
  return S.Result.getExn(S.parseWith(Js_dict.get(value.env, key), struct));
}

exports.get = get;
/* value Not a pure module */
